// <auto-generated />
using System;
using API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201114205353_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("API.Models.KeyExchange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyPEM")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("UserId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("KeyExchanges");
                });

            modelBuilder.Entity("API.Models.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DecryptedRecipientId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("MessageText")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("RecipientId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("SenderFingerprint")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("SenderId")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("SenderText")
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Sent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("API.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangeFingerprint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExchangePem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Modified")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreferredName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
